### PR TITLE
Creating a new random password generator file.

### PR DESCRIPTION
**Pull request by tausiq2003**
This password generator code is having only alphanumeric password to be
generated. Issue - #1 
**This PR is related to**: This is a random password generator code.
**Does it close the issue?**: No, I have created a new code, may be features
you can add to it.
**Summary**:
In this piece of code you can see I have entered a random
module from which some alphabets, digits and symbols are selected
randomly and without ordered which makes the password even stronger to
use(after adding a memory element and with certain encryption and
decrytption the code may be used in daily life.
**Other**:
Your issues are valuable to us.

### CODE REVIEW

**Comment by tausiq2003** [comment]
Screenshot 2021-09-22 223546

**Comment by tausiq2003** [comment]
Here is the code.

**Review by Akshu-on-github — APPROVED** [review]
LGTM ✅

**Comment by Akshu-on-github** [comment]
Hey there @tausiq2003! Thanks for contributing to the repo, I'll be merging the PR now 😃

**Comment by tausiq2003** [comment]
Thanks bro😊 i will contribute more new programs in future

**Pull request merged**
