### PR TITLE
Please accept my code

### PR DESCRIPTION
**Pull request by tausiq2003**
Hey there, I have added a code of password generator.
Hope you will like it.

**This PR is related to**: 

**Does it close the issue?**: 

**Summary**:

**Other**:

### CODE REVIEW

**Comment by Akshu-on-github** [comment]
@tausiq2003 - thanks for creating a PR
I'll review the addition soon - in the meantime, please fill in the indicated fields in the PR template

**Review by Akshu-on-github — CHANGES_REQUESTED** [review]
Hey there, few things that have to be corrected before merging:
- [ ] Throws an error around lines 6 and 7
- [ ] The file should be in the `./programs` folder
- [ ] Lack of comments/documentation

Apart from that, I'd suggest working on these points too:
_(Note: Please do let me know if you aren't up to it - I'll open up an issue for someone else)_
- [ ] User input for desired password length, and pre-requisites (Example: alphanumeric characters only)
- [ ] Follows standards for strong passwords (Example: a minimum of 8 and a maximum of 24 characters, contains at least one number, at least one special character, etc)

**Comment by Akshu-on-github** [comment]
Ah, one last thing, if I may: Please follow the naming convention for commits as mentioned in the `Contributing.md` file!

**Comment by tausiq2003** [comment]
what is the error showed in line6 and 7 can you show me please.

**Comment by tausiq2003** [comment]
Ok I read some of your request but some are contradicting.

**Comment by Akshu-on-github** [comment]
> Ok I read some of your request but some are contradicting.

Is there any point that's confusing? Do let me know, I'll do my best to clarify

> what is the error showed in line6 and 7 can you show me please.

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    password=''.join(random.choices(string.ascii_letters,k=passlen))
AttributeError: 'module' object has no attribute 'choices'
```
Here's the online Python IDE I used: [OnlineGDB](https://www.onlinegdb.com/online_python_compiler)

**Comment by tausiq2003** [comment]
but i have python 3.9 its showing may be the following be the issue:
https://stackoverflow.com/questions/25695412/module-object-has-no-attribute-choice-trying-to-use-random-choice
read this.

**Comment by tausiq2003** [comment]
should I use only alphanumeric or its user dependent

**Comment by tausiq2003** [comment]
Please answer

**Comment by tausiq2003** [comment]
its ok or i will change it please reply

**Comment by Akshu-on-github** [comment]
Hey @tausiq2003,

> https://stackoverflow.com/questions/25695412/module-object-has-no-attribute-choice-trying-to-use-random-choice
read this.

Yes, I am aware if you have a file or function with the same name as a python library, an error is thrown - I'm not sure how this applies to an online compiler since the files are non-persistent. Do you mean there might be a shadow copy of a previously used `random.py`?

Well, since it passes the linter, I'd say it's okay.

> its ok or i will change it please reply

Before I accept this PR, the following need to be done:
- [ ] Place the python script in the correct folder
- [ ] Add comments to document what you've done
- [ ] Fill in the PR details and rename the PR according to naming conventions

**Comment by tausiq2003** [comment]
Yes I will do, but you don't have to depend upon online compiler because in some cases it will throw error, also random.py should be renamed,  as random is a module in python. I will attach a screenshot at the time of pushing.

**Comment by Akshu-on-github** [comment]
> Yes I will do, but you don't have to depend upon online compiler because in some cases it will throw error

@tausiq2003 - The reason I test the code on an online compiler (before testing the same on my local device and the linter) is that those who aren't sure if they want to learn python intensely often use it. If there are errors thrown (like the one pointed out) please document them in the comments so that a beginner looking over the code knows that the fault is not on their end.

> Also random.py should be renamed, as random is a module in python. I will attach a screenshot at the time of pushing.


As far as I am aware, there is no `random.py` file in this repository. Please clarify?

**Comment by tausiq2003** [comment]
Ah ok, yeah there is not random file

**Pull request closed without merging**
