### PR TITLE
creating instagram profile picture downloader

### LINKED ISSUE #49: [CODE] add ig-downloader.py
**Topic**: Instagram profile picture downloader

**Reference(s) Used**: [instaloader Python library](https://instaloader.github.io/)

**Checklist**:

- [x] I have gone through the existing code samples - there are no duplicates
- [x] I have gone through the open PRs and Issues with the `sample code` label - there are no duplicates
- [x] I will create a PR to add the sample code
- [x] I have created a PR that adds the sample code
- [ ] I have updated the index appropriately

### PR DESCRIPTION
**Pull request by ObaidaHY**
**This PR is related to**: [CODE] add ig-downloader.py

**Does it close the issue?**: Y

**Summary**: using instaloader Python library to download instagram profile picture.
It's a good program to gain familiarity with basic use of some libraries.
In order to run the script you need to install [instaloader library](https://instaloader.github.io/).
Run the script, and use the Instagram username as input. a file with the desired photo will be created in the same directory as the code file.

### CODE REVIEW

**Comment by ObaidaHY** [comment]
#50 #49 
Screenshot (178)

Screenshot (179)

**Review by Akshu-on-github — CHANGES_REQUESTED** [review]
Hello there @ObaidaHY! I notice that you haven't updated the list of programs under `Programs/readme.md`
The rest looks good to me, I'll merge it once you do so

**Comment by ObaidaHY** [comment]
Done! @Akshu-on-github

**Review by Akshu-on-github — APPROVED** [review]

**Comment by Akshu-on-github** [comment]
Thanks for contributing to the project @ObaidaHY!

**Pull request merged**
