### PR TITLE
Create AN-LED-DISPLAY-SIMULATION.py

### PR DESCRIPTION
**Pull request by rahulsust**
[Maintainer Edit: 19-07-2021]

**This PR is related to**: #1 
**Does it close the issue?**: N
**Summary**: A python program that displays ASCII art of numbers similar to an LED display

### CODE REVIEW

**Comment by rahulsust** [comment]
I would like to add this programme.

**Review by Akshu-on-github — CHANGES_REQUESTED** [review]
Whoa, this seems really neat! A few features I'd request:
- Repeated user input
- Increased spacing between digits (for example 123)
- A prompt to enter input that defines the sample space
- Error handling (if it's not a number, you could try printing 'NaN', a frowny face, etc.)

You needn't work on all of these - let me know what you can/want to work on right now, and I'll put the rest up in a separate issue

**Comment by rahulsust** [comment]
I can work on all the features you suggested

**Comment by Akshu-on-github** [comment]
Awesome! I'll merge the PR for now - please create a new issue and PR for the same! And oh, please reference my code review if you can

**Pull request merged**
